# Generated by Django 3.2.7 on 2021-09-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swatch_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rgbswatch',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rgbswatch',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rgbswatch',
            name='red',
            field=models.IntegerField(default=0),
        ),
    ]
